name: Pull Request To Dev
run-name: Run Integration Tests
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Run  app.cpp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Give chmod
        run: chmod +x app.cpp
      - name: Run test
        run: source tests/unit-test.sh
